export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const GOOGLE_LOGIN_USER_REQUESTED = 'GOOGLE_LOGIN_USER_REQUESTED';
export const REGISTER_CONTRIBUTOR_REQUESTED = 'REGISTER_CONTRIBUTOR_REQUESTED';
export const REGISTER_ORGANIZATION_REQUESTED = 'REGISTER_ORGANIZATION_REQUESTED';
export const VERIFY_ORGANIZATION_REQUESTED = 'VERIFY_ORGANIZATION_REQUESTED';
export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const SEND_OTP_REQUESTED = 'SEND_OTP_REQUESTED';
export const VERIFY_OTP_REQUESTED = 'VERIFY_OTP_REQUESTED';