export const ORGANIZATION_CREATE_REQUEST = 'ORGANIZATION_CREATE_REQUEST';
export const FETCH_ORGANIZATION_CURRENT_REQUEST = 'FETCH_ORGANIZATION_CURRENT_REQUEST';
export const FETCH_ORGANIZATION_COMPLETED_REQUEST = 'FETCH_ORGANIZATION_COMPLETED_REQUEST';
export const FETCH_CONTRIBUTOR_SEARCH_REQUEST = 'FETCH_CONTRIBUTOR_SEARCH_REQUEST';
export const FETCH_CONTRIBUTOR_CURRENT_REQUEST = 'FETCH_CONTRIBUTOR_CURRENT_REQUEST';
export const FETCH_CONTRIBUTOR_COMPLETED_REQUEST = 'FETCH_CONTRIBUTOR_COMPLETED_REQUEST';
export const DONATE_CONTRIBUTOR_REQUEST = 'DONATE_CONTRIBUTOR_REQUEST';
export const ACKNOWLEDGE_CONTRIBUTOR_REQUEST = 'ACKNOWLEDGE_CONTRIBUTOR_REQUEST';